server:
  port: 83

spring:
  application:
    name: alibaba-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.129:8848

server-url:
  nacos-service-provider: http://nacos-provider